/**
 * Content Production Project Template
 * Complete content creation and publishing workflow
 */

import { ProjectTemplate } from '../types/projectTemplate.types';

export const contentProductionTemplate: ProjectTemplate = {
  id: 'content-production-v1',
  name: 'Content Production Pipeline',
  description: 'End-to-end content creation workflow from ideation to publishing',
  industry: ['Content', 'Media', 'Publishing'],
  category: 'content',
  icon: 'PenTool',
  coverImage: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800',
  difficulty: 'intermediate',
  estimatedSetupTime: '10 minutes',
  
  boards: [
    {
      id: 'content-ideation',
      name: 'Content Ideation',
      description: 'Generate and organize content ideas',
      icon: 'Lightbulb',
      color: '#00C6FF',
      tasks: [
        {
          id: 'ai-topic-generator',
          title: 'Set up AI topic generator',
          description: 'Use AI to generate content ideas',
          status: 'todo',
          priority: 'high',
          tags: ['ai', 'ideation'],
          workflowId: 'ai-content-ideas',
          dueDate: '+1d',
        },
        {
          id: 'trend-monitoring',
          title: 'Monitor trending topics',
          description: 'Track trending topics in your niche',
          status: 'todo',
          priority: 'medium',
          tags: ['trends', 'research'],
          workflowId: 'trend-monitor',
          dueDate: '+2d',
        },
        {
          id: 'keyword-research',
          title: 'Automate keyword research',
          description: 'Find high-volume keywords',
          status: 'todo',
          priority: 'medium',
          tags: ['seo', 'research'],
          workflowId: 'keyword-researcher',
          dueDate: '+3d',
        },
      ],
    },
    {
      id: 'content-creation',
      name: 'Content Creation',
      description: 'Write and design content',
      icon: 'Edit',
      color: '#9D50BB',
      tasks: [
        {
          id: 'ai-writing-assistant',
          title: 'Enable AI writing assistant',
          description: 'Generate blog post drafts with AI',
          status: 'todo',
          priority: 'high',
          tags: ['ai', 'writing'],
          workflowId: 'ai-blog-writer',
          dueDate: '+2d',
        },
        {
          id: 'image-generation',
          title: 'Set up image automation',
          description: 'Auto-generate featured images',
          status: 'todo',
          priority: 'medium',
          tags: ['images', 'design'],
          workflowId: 'image-generator',
          dueDate: '+3d',
        },
        {
          id: 'seo-optimization',
          title: 'Automate SEO optimization',
          description: 'Optimize content for search engines',
          status: 'todo',
          priority: 'high',
          tags: ['seo', 'optimization'],
          workflowId: 'seo-optimizer',
          dueDate: '+2d',
        },
      ],
    },
    {
      id: 'review-approval',
      name: 'Review & Approval',
      description: 'Editorial review and approval chain',
      icon: 'CheckCircle',
      color: '#F59E0B',
      tasks: [
        {
          id: 'editor-assignment',
          title: 'Auto-assign to editor',
          description: 'Route content to available editor',
          status: 'todo',
          priority: 'high',
          tags: ['workflow', 'assignment'],
          workflowId: 'editor-router',
          dueDate: '+2d',
        },
        {
          id: 'approval-workflow',
          title: 'Set up approval chain',
          description: 'Multi-level approval process',
          status: 'todo',
          priority: 'high',
          tags: ['workflow', 'approval'],
          workflowId: 'content-approval-chain',
          dueDate: '+3d',
        },
        {
          id: 'plagiarism-check',
          title: 'Automated plagiarism check',
          description: 'Check content originality',
          status: 'todo',
          priority: 'medium',
          tags: ['quality', 'checking'],
          workflowId: 'plagiarism-checker',
          dueDate: '+4d',
        },
      ],
    },
    {
      id: 'publishing',
      name: 'Publishing & Distribution',
      description: 'Publish and promote content',
      icon: 'Rocket',
      color: '#6EE7B7',
      tasks: [
        {
          id: 'cms-publishing',
          title: 'Auto-publish to CMS',
          description: 'Publish approved content to WordPress/etc',
          status: 'todo',
          priority: 'high',
          tags: ['publishing', 'cms'],
          workflowId: 'cms-auto-publish',
          dueDate: '+2d',
        },
        {
          id: 'social-sharing',
          title: 'Share on social media',
          description: 'Auto-post to social channels',
          status: 'todo',
          priority: 'high',
          tags: ['social', 'distribution'],
          workflowId: 'social-auto-share',
          dueDate: '+3d',
        },
        {
          id: 'newsletter-feature',
          title: 'Feature in newsletter',
          description: 'Add to weekly newsletter',
          status: 'todo',
          priority: 'medium',
          tags: ['email', 'newsletter'],
          workflowId: 'newsletter-inclusion',
          dueDate: '+4d',
        },
        {
          id: 'performance-tracking',
          title: 'Track content performance',
          description: 'Monitor views, engagement, SEO rankings',
          status: 'todo',
          priority: 'medium',
          tags: ['analytics', 'tracking'],
          workflowId: 'content-analytics',
          dueDate: '+5d',
        },
      ],
    },
  ],
  
  workflows: [],
  
  requiredIntegrations: ['WordPress/CMS', 'OpenAI', 'Google Analytics'],
  requiredApiKeys: [
    {
      key: 'WORDPRESS_API_KEY',
      label: 'WordPress/CMS API Key',
      description: 'For publishing content',
      placeholder: '',
      required: true,
    },
    {
      key: 'OPENAI_API_KEY',
      label: 'OpenAI API Key',
      description: 'For AI content generation',
      placeholder: 'sk-...',
      required: true,
    },
    {
      key: 'TWITTER_API_KEY',
      label: 'Twitter API Key',
      description: 'For social media sharing',
      placeholder: '',
      required: false,
    },
    {
      key: 'SENDGRID_API_KEY',
      label: 'SendGrid API Key',
      description: 'For newsletter distribution',
      placeholder: 'SG...',
      required: false,
    },
  ],
  
  configurationSteps: [
    'Connect your CMS platform',
    'Set up AI content generation',
    'Configure approval workflow',
    'Link social media accounts',
    'Activate publishing automation',
  ],
  
  tags: ['content', 'blogging', 'publishing', 'ai', 'seo'],
  useCases: [
    'Generate content ideas with AI',
    'Write blog posts faster with AI assistance',
    'Automate editorial approval process',
    'Publish to multiple platforms simultaneously',
    'Track content performance and ROI',
  ],
  benefits: [
    'Produce 3x more content with same team',
    'Reduce content creation time by 60%',
    'Maintain consistent publishing schedule',
    'Improve SEO rankings with optimized content',
    'Scale content operations efficiently',
  ],
  
  author: 'Flowversal Team',
  featured: false,
  usageCount: 98,
  createdAt: new Date('2024-01-28').toISOString(),
  updatedAt: new Date('2024-01-28').toISOString(),
};
