/**
 * Customer Support Project Template
 * Automated ticket management and customer service workflows
 */

import { ProjectTemplate } from '../types/projectTemplate.types';

export const customerSupportTemplate: ProjectTemplate = {
  id: 'customer-support-v1',
  name: 'Customer Support Hub',
  description: 'Intelligent ticket routing, automated responses, and customer satisfaction tracking',
  industry: ['Customer Service', 'SaaS', 'Support'],
  category: 'customer-support',
  icon: 'Headphones',
  coverImage: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800',
  difficulty: 'beginner',
  estimatedSetupTime: '7 minutes',
  
  boards: [
    {
      id: 'ticket-management',
      name: 'Ticket Management',
      description: 'Automated ticket routing and responses',
      icon: 'Ticket',
      color: '#00C6FF',
      tasks: [
        {
          id: 'ticket-routing',
          title: 'Set up ticket routing',
          description: 'Auto-route tickets to the right team',
          status: 'todo',
          priority: 'high',
          tags: ['tickets', 'automation'],
          workflowId: 'ticket-routing-system',
          dueDate: '+1d',
        },
        {
          id: 'auto-responses',
          title: 'Configure auto-responses',
          description: 'Send instant acknowledgment emails',
          status: 'todo',
          priority: 'high',
          tags: ['email', 'automation'],
          workflowId: 'ticket-auto-response',
          dueDate: '+1d',
        },
        {
          id: 'priority-tagging',
          title: 'Auto-tag ticket priority',
          description: 'Automatically assign priority levels',
          status: 'todo',
          priority: 'medium',
          tags: ['tickets', 'tagging'],
          workflowId: 'priority-tagging',
          dueDate: '+2d',
        },
        {
          id: 'escalation',
          title: 'Set up escalation rules',
          description: 'Escalate unresolved tickets automatically',
          status: 'todo',
          priority: 'high',
          tags: ['tickets', 'escalation'],
          workflowId: 'ticket-escalation',
          dueDate: '+3d',
        },
      ],
    },
    {
      id: 'knowledge-base',
      name: 'Knowledge Base',
      description: 'Self-service resources and AI responses',
      icon: 'BookOpen',
      color: '#9D50BB',
      tasks: [
        {
          id: 'ai-suggestions',
          title: 'Enable AI article suggestions',
          description: 'Suggest relevant KB articles to customers',
          status: 'todo',
          priority: 'medium',
          tags: ['ai', 'knowledge-base'],
          workflowId: 'kb-article-suggester',
          dueDate: '+3d',
        },
        {
          id: 'chat-bot',
          title: 'Deploy AI chatbot',
          description: 'Answer common questions automatically',
          status: 'todo',
          priority: 'high',
          tags: ['ai', 'chatbot'],
          workflowId: 'ai-support-chatbot',
          dueDate: '+4d',
        },
      ],
    },
    {
      id: 'customer-feedback',
      name: 'Customer Feedback',
      description: 'Collect and act on customer feedback',
      icon: 'Star',
      color: '#F59E0B',
      tasks: [
        {
          id: 'csat-survey',
          title: 'Send CSAT surveys',
          description: 'Automatically send satisfaction surveys',
          status: 'todo',
          priority: 'high',
          tags: ['feedback', 'surveys'],
          workflowId: 'csat-survey-automation',
          dueDate: '+2d',
        },
        {
          id: 'nps-tracking',
          title: 'Track NPS scores',
          description: 'Monitor Net Promoter Score trends',
          status: 'todo',
          priority: 'medium',
          tags: ['feedback', 'nps'],
          workflowId: 'nps-tracker',
          dueDate: '+4d',
        },
        {
          id: 'negative-feedback-alert',
          title: 'Alert on negative feedback',
          description: 'Notify team of low ratings',
          status: 'todo',
          priority: 'high',
          tags: ['alerts', 'feedback'],
          workflowId: 'negative-feedback-alert',
          dueDate: '+2d',
        },
      ],
    },
    {
      id: 'team-performance',
      name: 'Team Performance',
      description: 'Support team metrics and reporting',
      icon: 'BarChart',
      color: '#6EE7B7',
      tasks: [
        {
          id: 'daily-metrics',
          title: 'Daily support metrics',
          description: 'Send daily performance report to team',
          status: 'todo',
          priority: 'medium',
          tags: ['reporting', 'metrics'],
          workflowId: 'daily-support-report',
          dueDate: '+3d',
        },
        {
          id: 'sla-monitoring',
          title: 'Monitor SLA compliance',
          description: 'Track response and resolution times',
          status: 'todo',
          priority: 'high',
          tags: ['sla', 'monitoring'],
          workflowId: 'sla-monitor',
          dueDate: '+2d',
        },
      ],
    },
  ],
  
  workflows: [],
  
  requiredIntegrations: ['Zendesk/Intercom', 'SendGrid', 'Slack'],
  requiredApiKeys: [
    {
      key: 'SUPPORT_PLATFORM_API_KEY',
      label: 'Support Platform API Key',
      description: 'API key for Zendesk, Intercom, or Freshdesk',
      placeholder: '',
      required: true,
    },
    {
      key: 'SENDGRID_API_KEY',
      label: 'SendGrid API Key',
      description: 'For sending customer emails',
      placeholder: 'SG...',
      required: true,
    },
    {
      key: 'OPENAI_API_KEY',
      label: 'OpenAI API Key',
      description: 'For AI-powered responses (optional)',
      placeholder: 'sk-...',
      required: false,
    },
  ],
  
  configurationSteps: [
    'Connect your support platform',
    'Set up email notifications',
    'Configure routing rules',
    'Enable AI features (optional)',
    'Activate workflows',
  ],
  
  tags: ['support', 'tickets', 'customer-service', 'automation', 'ai'],
  useCases: [
    'Route tickets to the right agent instantly',
    'Send automated acknowledgment emails',
    'Escalate urgent issues automatically',
    'Deploy AI chatbot for common questions',
    'Track customer satisfaction metrics',
  ],
  benefits: [
    'Reduce response time by 60%',
    'Improve CSAT scores by 25%',
    'Handle 40% more tickets with same team',
    'Never miss an SLA deadline',
    'Identify trends and improve processes',
  ],
  
  author: 'Flowversal Team',
  featured: true,
  usageCount: 203,
  createdAt: new Date('2024-01-22').toISOString(),
  updatedAt: new Date('2024-01-22').toISOString(),
};
