/**
 * HR Onboarding Project Template
 * Complete employee onboarding automation system
 */

import { ProjectTemplate } from '../types/projectTemplate.types';

export const hrOnboardingTemplate: ProjectTemplate = {
  id: 'hr-onboarding-v1',
  name: 'Employee Onboarding System',
  description: 'Streamlined employee onboarding with document collection, training, and IT setup automation',
  industry: ['HR', 'Human Resources', 'People Operations'],
  category: 'hr',
  icon: 'Users',
  coverImage: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800',
  difficulty: 'beginner',
  estimatedSetupTime: '9 minutes',
  
  boards: [
    {
      id: 'pre-boarding',
      name: 'Pre-boarding',
      description: 'Tasks before the first day',
      icon: 'ClipboardList',
      color: '#00C6FF',
      tasks: [
        {
          id: 'welcome-email',
          title: 'Send welcome email',
          description: 'Automated welcome email to new hire',
          status: 'todo',
          priority: 'high',
          tags: ['email', 'welcome'],
          workflowId: 'new-hire-welcome-email',
          dueDate: '+1d',
        },
        {
          id: 'document-collection',
          title: 'Collect required documents',
          description: 'Request tax forms, ID, etc.',
          status: 'todo',
          priority: 'high',
          tags: ['documents', 'compliance'],
          workflowId: 'document-collection',
          dueDate: '+1d',
        },
        {
          id: 'equipment-order',
          title: 'Order equipment',
          description: 'Trigger laptop and equipment orders',
          status: 'todo',
          priority: 'high',
          tags: ['it', 'equipment'],
          workflowId: 'equipment-ordering',
          dueDate: '+2d',
        },
        {
          id: 'account-setup',
          title: 'Create user accounts',
          description: 'Set up email, Slack, and other accounts',
          status: 'todo',
          priority: 'high',
          tags: ['it', 'accounts'],
          workflowId: 'account-provisioning',
          dueDate: '+2d',
        },
      ],
    },
    {
      id: 'first-day',
      name: 'First Day',
      description: 'First day checklist and activities',
      icon: 'Calendar',
      color: '#9D50BB',
      tasks: [
        {
          id: 'team-introduction',
          title: 'Send team introduction',
          description: 'Introduce new hire to the team',
          status: 'todo',
          priority: 'high',
          tags: ['communication', 'team'],
          workflowId: 'team-introduction-email',
          dueDate: '+1d',
        },
        {
          id: 'orientation-schedule',
          title: 'Schedule orientation sessions',
          description: 'Book calendar for orientation activities',
          status: 'todo',
          priority: 'high',
          tags: ['scheduling', 'orientation'],
          workflowId: 'orientation-scheduler',
          dueDate: '+2d',
        },
        {
          id: 'workspace-setup',
          title: 'Prepare workspace',
          description: 'Set up desk, access cards, etc.',
          status: 'todo',
          priority: 'medium',
          tags: ['facilities', 'setup'],
          dueDate: '+1d',
        },
      ],
    },
    {
      id: 'first-week',
      name: 'First Week',
      description: 'Week 1 training and setup',
      icon: 'BookOpen',
      color: '#F59E0B',
      tasks: [
        {
          id: 'training-modules',
          title: 'Assign training modules',
          description: 'Send links to required training',
          status: 'todo',
          priority: 'high',
          tags: ['training', 'learning'],
          workflowId: 'training-assignment',
          dueDate: '+3d',
        },
        {
          id: 'buddy-assignment',
          title: 'Assign onboarding buddy',
          description: 'Match with experienced team member',
          status: 'todo',
          priority: 'medium',
          tags: ['mentorship', 'team'],
          workflowId: 'buddy-matcher',
          dueDate: '+2d',
        },
        {
          id: 'checkin-meeting',
          title: 'Schedule check-in meetings',
          description: 'Daily check-ins with manager',
          status: 'todo',
          priority: 'medium',
          tags: ['meetings', 'management'],
          dueDate: '+3d',
        },
      ],
    },
    {
      id: 'first-month',
      name: 'First Month',
      description: '30-day onboarding milestones',
      icon: 'Target',
      color: '#6EE7B7',
      tasks: [
        {
          id: '30-day-survey',
          title: 'Send 30-day feedback survey',
          description: 'Collect new hire experience feedback',
          status: 'todo',
          priority: 'high',
          tags: ['feedback', 'survey'],
          workflowId: '30-day-survey',
          dueDate: '+30d',
        },
        {
          id: 'performance-review',
          title: 'Schedule 30-day review',
          description: 'First performance check-in',
          status: 'todo',
          priority: 'high',
          tags: ['performance', 'review'],
          dueDate: '+28d',
        },
        {
          id: 'benefits-enrollment',
          title: 'Complete benefits enrollment',
          description: 'Finalize health insurance, 401k, etc.',
          status: 'todo',
          priority: 'medium',
          tags: ['benefits', 'hr'],
          workflowId: 'benefits-reminder',
          dueDate: '+25d',
        },
      ],
    },
  ],
  
  workflows: [],
  
  requiredIntegrations: ['Google Workspace/Microsoft 365', 'Slack', 'DocuSign'],
  requiredApiKeys: [
    {
      key: 'GOOGLE_WORKSPACE_KEY',
      label: 'Google Workspace API Key',
      description: 'For creating user accounts',
      placeholder: '',
      required: false,
    },
    {
      key: 'SLACK_API_KEY',
      label: 'Slack API Key',
      description: 'For Slack account creation',
      placeholder: '',
      required: false,
    },
    {
      key: 'DOCUSIGN_API_KEY',
      label: 'DocuSign API Key',
      description: 'For document signing workflows',
      placeholder: '',
      required: false,
    },
    {
      key: 'SENDGRID_API_KEY',
      label: 'SendGrid API Key',
      description: 'For sending onboarding emails',
      placeholder: 'SG...',
      required: true,
    },
  ],
  
  configurationSteps: [
    'Connect email service',
    'Set up document collection',
    'Configure IT provisioning',
    'Customize training materials',
    'Activate onboarding workflows',
  ],
  
  tags: ['hr', 'onboarding', 'employees', 'automation', 'training'],
  useCases: [
    'Automate new hire paperwork collection',
    'Provision IT accounts and equipment',
    'Schedule orientation and training',
    'Track onboarding progress',
    'Collect feedback and improve process',
  ],
  benefits: [
    'Reduce onboarding time by 50%',
    'Improve new hire satisfaction by 40%',
    'Never forget critical onboarding steps',
    'Save 10+ hours per new hire',
    'Create consistent onboarding experience',
  ],
  
  author: 'Flowversal Team',
  featured: false,
  usageCount: 134,
  createdAt: new Date('2024-01-25').toISOString(),
  updatedAt: new Date('2024-01-25').toISOString(),
};
