/**
 * Sales Pipeline Project Template
 * Complete CRM automation for lead management and sales processes
 */

import { ProjectTemplate } from '../types/projectTemplate.types';

export const salesPipelineTemplate: ProjectTemplate = {
  id: 'sales-pipeline-v1',
  name: 'Sales Pipeline Automation',
  description: 'Automated lead scoring, follow-ups, and CRM synchronization for sales teams',
  industry: ['Sales', 'B2B', 'SaaS'],
  category: 'sales',
  icon: 'Briefcase',
  coverImage: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
  difficulty: 'intermediate',
  estimatedSetupTime: '12 minutes',
  
  boards: [
    {
      id: 'lead-management',
      name: 'Lead Management',
      description: 'Capture, score, and qualify leads',
      icon: 'Target',
      color: '#00C6FF',
      tasks: [
        {
          id: 'lead-capture',
          title: 'Set up lead capture forms',
          description: 'Automatically capture leads from website forms',
          status: 'todo',
          priority: 'high',
          tags: ['leads', 'forms'],
          workflowId: 'lead-capture-form',
          dueDate: '+1d',
        },
        {
          id: 'lead-scoring',
          title: 'Configure lead scoring',
          description: 'Score leads based on behavior and demographics',
          status: 'todo',
          priority: 'high',
          tags: ['leads', 'scoring'],
          workflowId: 'lead-scoring-system',
          dueDate: '+2d',
        },
        {
          id: 'lead-qualification',
          title: 'Automate lead qualification',
          description: 'Automatically qualify leads as MQL/SQL',
          status: 'todo',
          priority: 'medium',
          tags: ['leads', 'qualification'],
          workflowId: 'lead-qualification',
          dueDate: '+3d',
        },
        {
          id: 'lead-routing',
          title: 'Set up lead routing',
          description: 'Route leads to appropriate sales reps',
          status: 'todo',
          priority: 'high',
          tags: ['leads', 'routing'],
          workflowId: 'lead-routing-system',
          dueDate: '+2d',
        },
      ],
    },
    {
      id: 'follow-ups',
      name: 'Follow-up Sequences',
      description: 'Automated email and task follow-ups',
      icon: 'Inbox',
      color: '#9D50BB',
      tasks: [
        {
          id: 'initial-contact',
          title: 'Create initial contact sequence',
          description: '3-step email sequence for new leads',
          status: 'todo',
          priority: 'high',
          tags: ['email', 'follow-up'],
          workflowId: 'initial-contact-sequence',
          dueDate: '+2d',
        },
        {
          id: 'demo-follow-up',
          title: 'Set up demo follow-up',
          description: 'Follow-up sequence after demos',
          status: 'todo',
          priority: 'high',
          tags: ['email', 'demo'],
          workflowId: 'demo-follow-up-sequence',
          dueDate: '+3d',
        },
        {
          id: 'proposal-reminder',
          title: 'Automate proposal reminders',
          description: 'Remind prospects about pending proposals',
          status: 'todo',
          priority: 'medium',
          tags: ['email', 'proposals'],
          workflowId: 'proposal-reminder',
          dueDate: '+4d',
        },
      ],
    },
    {
      id: 'crm-sync',
      name: 'CRM Integration',
      description: 'Sync with Salesforce, HubSpot, or Pipedrive',
      icon: 'RefreshCw',
      color: '#F59E0B',
      tasks: [
        {
          id: 'crm-connection',
          title: 'Connect CRM system',
          description: 'Integrate with your CRM platform',
          status: 'todo',
          priority: 'high',
          tags: ['crm', 'integration'],
          dueDate: '+1d',
        },
        {
          id: 'contact-sync',
          title: 'Sync contacts automatically',
          description: 'Two-way contact synchronization',
          status: 'todo',
          priority: 'high',
          tags: ['crm', 'sync'],
          workflowId: 'crm-contact-sync',
          dueDate: '+2d',
        },
        {
          id: 'deal-tracking',
          title: 'Track deal progression',
          description: 'Auto-update deal stages in CRM',
          status: 'todo',
          priority: 'medium',
          tags: ['crm', 'deals'],
          workflowId: 'deal-stage-tracker',
          dueDate: '+3d',
        },
      ],
    },
    {
      id: 'sales-analytics',
      name: 'Sales Analytics',
      description: 'Performance tracking and reporting',
      icon: 'BarChart',
      color: '#6EE7B7',
      tasks: [
        {
          id: 'pipeline-report',
          title: 'Daily pipeline report',
          description: 'Send daily pipeline summary to team',
          status: 'todo',
          priority: 'high',
          tags: ['reporting', 'pipeline'],
          workflowId: 'daily-pipeline-report',
          dueDate: '+3d',
        },
        {
          id: 'win-loss-analysis',
          title: 'Track win/loss metrics',
          description: 'Analyze closed deals for insights',
          status: 'todo',
          priority: 'medium',
          tags: ['analytics', 'deals'],
          dueDate: '+4d',
        },
      ],
    },
  ],
  
  workflows: [],
  
  requiredIntegrations: ['Salesforce/HubSpot', 'SendGrid', 'Slack'],
  requiredApiKeys: [
    {
      key: 'CRM_API_KEY',
      label: 'CRM API Key',
      description: 'API key for your CRM (Salesforce, HubSpot, etc.)',
      placeholder: '',
      required: true,
    },
    {
      key: 'SENDGRID_API_KEY',
      label: 'SendGrid API Key',
      description: 'For sending follow-up emails',
      placeholder: 'SG...',
      required: true,
    },
    {
      key: 'SLACK_WEBHOOK_URL',
      label: 'Slack Webhook URL',
      description: 'For lead and deal notifications',
      placeholder: 'https://hooks.slack.com/services/...',
      required: false,
    },
  ],
  
  configurationSteps: [
    'Connect your CRM system',
    'Set up email service for follow-ups',
    'Configure lead scoring rules',
    'Set up notification channels',
    'Activate automation workflows',
  ],
  
  tags: ['sales', 'crm', 'leads', 'automation', 'pipeline'],
  useCases: [
    'Automate lead capture and qualification',
    'Score and prioritize leads intelligently',
    'Send timely follow-up emails',
    'Keep CRM data synchronized',
    'Track sales pipeline in real-time',
  ],
  benefits: [
    'Increase lead conversion by 35%',
    'Save 20+ hours per week on manual tasks',
    'Never miss a follow-up',
    'Make data-driven sales decisions',
    'Reduce sales cycle time by 25%',
  ],
  
  author: 'Flowversal Team',
  featured: true,
  usageCount: 156,
  createdAt: new Date('2024-01-18').toISOString(),
  updatedAt: new Date('2024-01-18').toISOString(),
};
