import { ArrowLeft, Copy, Download, Bold, Italic, Underline, List, ListOrdered, CheckSquare, MoreHorizontal } from 'lucide-react';
import { useState } from 'react';
import { useTheme } from '@/core/theme/ThemeContext';

interface WorkflowDetailProps {
  workflowName: string;
  onBack: () => void;
}

export function WorkflowDetail({ workflowName, onBack }: WorkflowDetailProps) {
  const { theme } = useTheme();
  const [formData, setFormData] = useState({
    businessAbout: '',
  });
  const [result, setResult] = useState('');
  const [advancedOpen, setAdvancedOpen] = useState(false);

  const handleSubmit = () => {
    // Simulate content generation
    setResult(`Generated content based on: ${formData.businessAbout}\n\nThis is a sample result that would be generated by the AI tool. The actual implementation would call an API to generate real content based on the workflow type and user inputs.`);
  };

  const bgMain = theme === 'dark' ? 'bg-[#0E0E1F]' : 'bg-gray-50';
  const bgCard = theme === 'dark' ? 'bg-[#1A1A2E]' : 'bg-white';
  const textPrimary = theme === 'dark' ? 'text-white' : 'text-gray-900';
  const textSecondary = theme === 'dark' ? 'text-[#CFCFE8]' : 'text-gray-600';
  const borderColor = theme === 'dark' ? 'border-white/10' : 'border-gray-200';

  return (
    <div className={`min-h-screen ${bgMain} transition-colors duration-300`}>
      {/* Main Content */}
      <div className="mt-16 p-8 flex gap-6 h-[calc(100vh-64px)]">
        {/* Left Form Panel */}
        <div className={`w-[400px] ${bgCard} rounded-xl border ${borderColor} flex flex-col`}>
          {/* Back Button Inside Panel */}
          <div className={`px-6 pt-6 pb-4 border-b ${borderColor}`}>
            <button
              onClick={onBack}
              className={`flex items-center gap-2 px-4 py-2 rounded-lg ${theme === 'dark' ? 'bg-[#0E0E1F]' : 'bg-gray-100'} border ${borderColor} ${textPrimary} hover:bg-gradient-to-r hover:from-[#00C6FF]/10 hover:to-[#9D50BB]/10 transition-all w-full justify-center`}
            >
              <ArrowLeft className="w-5 h-5 text-[#00C6FF]" />
              <span>Back to Workflows</span>
            </button>
          </div>

          <div className="flex-1 overflow-y-auto p-6">
            {/* Title */}
            <div className="mb-6">
              <h2 className={`text-2xl ${textPrimary} mb-2`}>{workflowName}</h2>
              <p className={`text-sm ${textSecondary}`}>
                This tool helps optimize your page with keyword variations, related keywords, SEO-friendly title...
                <button className="ml-1 text-[#00C6FF] hover:underline">more</button>
              </p>
            </div>

            {/* Question 1 */}
            <div className="mb-6">
              <div className="flex items-center gap-2 mb-3">
                <span className="text-[#00C6FF]">1</span>
                <label className={`${textPrimary} flex items-center gap-2`}>
                  <span>📝</span>
                  <span>What's Your Business About?</span>
                </label>
              </div>
              <textarea
                value={formData.businessAbout}
                onChange={(e) => setFormData({ ...formData, businessAbout: e.target.value })}
                placeholder="Example: A landscaping company in Tempe Arizona"
                className={`w-full h-32 ${bgMain} border ${borderColor} rounded-lg px-4 py-3 ${textPrimary} placeholder:${textSecondary} focus:outline-none focus:border-[#00C6FF]/50 focus:ring-2 focus:ring-[#00C6FF]/20 transition-all resize-none`}
              />
            </div>

            {/* Advanced Settings */}
            <div className="mb-6">
              <button
                onClick={() => setAdvancedOpen(!advancedOpen)}
                className={`flex items-center justify-between w-full ${textPrimary} hover:${textSecondary} transition-colors`}
              >
                <div className="flex items-center gap-2">
                  <span className="text-[#00C6FF]">2</span>
                  <span>Advanced Settings</span>
                  <span className={`text-sm ${textSecondary}`}>(optional)</span>
                </div>
                <span className={`transform transition-transform ${advancedOpen ? 'rotate-180' : ''}`}>▼</span>
              </button>
              {advancedOpen && (
                <div className={`mt-4 p-4 ${bgMain} rounded-lg border ${borderColor}`}>
                  <p className={`text-sm ${textSecondary}`}>Advanced options would appear here...</p>
                </div>
              )}
            </div>
          </div>

          {/* Submit Button */}
          <div className={`p-6 border-t ${borderColor}`}>
            <button
              onClick={handleSubmit}
              className="w-full py-3 rounded-lg bg-gradient-to-r from-[#00C6FF] via-[#0072FF] to-[#9D50BB] text-white hover:shadow-lg hover:shadow-[#00C6FF]/50 transition-all flex items-center justify-center gap-2"
            >
              <span>Submit</span>
            </button>
          </div>
        </div>

        {/* Right Result Panel */}
        <div className={`flex-1 ${bgCard} rounded-xl border ${borderColor} flex flex-col`}>
          {/* Header */}
          <div className={`flex items-center justify-between px-6 py-4 border-b ${borderColor}`}>
            <h3 className={`text-lg ${textPrimary}`}>Your Result</h3>
            <div className="flex items-center gap-2">
              <button className="px-4 py-2 rounded-lg bg-gradient-to-r from-[#00C6FF]/20 to-[#9D50BB]/20 text-[#00C6FF] hover:from-[#00C6FF]/30 hover:to-[#9D50BB]/30 transition-all">
                Save
              </button>
              <button className={`w-9 h-9 rounded-lg ${bgMain} border ${borderColor} flex items-center justify-center hover:border-[#00C6FF]/50 transition-all`}>
                <Copy className="w-4 h-4 text-[#CFCFE8]" />
              </button>
              <button className={`w-9 h-9 rounded-lg ${bgMain} border ${borderColor} flex items-center justify-center hover:border-[#00C6FF]/50 transition-all`}>
                <Download className="w-4 h-4 text-[#CFCFE8]" />
              </button>
            </div>
          </div>

          {/* Toolbar */}
          <div className={`flex items-center gap-2 px-6 py-3 border-b ${borderColor}`}>
            <button className={`w-8 h-8 rounded flex items-center justify-center hover:bg-gradient-to-r hover:from-[#00C6FF]/10 hover:to-[#9D50BB]/10 transition-all ${textSecondary}`}>
              <Bold className="w-4 h-4" />
            </button>
            <button className={`w-8 h-8 rounded flex items-center justify-center hover:bg-gradient-to-r hover:from-[#00C6FF]/10 hover:to-[#9D50BB]/10 transition-all ${textSecondary}`}>
              <Italic className="w-4 h-4" />
            </button>
            <button className={`w-8 h-8 rounded flex items-center justify-center hover:bg-gradient-to-r hover:from-[#00C6FF]/10 hover:to-[#9D50BB]/10 transition-all ${textSecondary}`}>
              <Underline className="w-4 h-4" />
            </button>
            <div className={`w-px h-6 ${borderColor} bg-current mx-1`}></div>
            <button className={`w-8 h-8 rounded flex items-center justify-center hover:bg-gradient-to-r hover:from-[#00C6FF]/10 hover:to-[#9D50BB]/10 transition-all ${textSecondary}`}>
              <List className="w-4 h-4" />
            </button>
            <button className={`w-8 h-8 rounded flex items-center justify-center hover:bg-gradient-to-r hover:from-[#00C6FF]/10 hover:to-[#9D50BB]/10 transition-all ${textSecondary}`}>
              <ListOrdered className="w-4 h-4" />
            </button>
            <button className={`w-8 h-8 rounded flex items-center justify-center hover:bg-gradient-to-r hover:from-[#00C6FF]/10 hover:to-[#9D50BB]/10 transition-all ${textSecondary}`}>
              <CheckSquare className="w-4 h-4" />
            </button>
            <div className={`w-px h-6 ${borderColor} bg-current mx-1`}></div>
            <button className={`w-8 h-8 rounded flex items-center justify-center hover:bg-gradient-to-r hover:from-[#00C6FF]/10 hover:to-[#9D50BB]/10 transition-all ${textSecondary}`}>
              <MoreHorizontal className="w-4 h-4" />
            </button>
          </div>

          {/* Content Area */}
          <div className="flex-1 overflow-y-auto p-6">
            {result ? (
              <div className={`${textPrimary} whitespace-pre-wrap`}>{result}</div>
            ) : (
              <div className={`flex items-center justify-center h-full ${textSecondary}`}>
                <p>Fill out the form and click "Submit" to see results here</p>
              </div>
            )}
          </div>

          {/* Footer Note */}
          <div className={`px-6 py-3 border-t ${borderColor}`}>
            <p className={`text-xs text-center ${textSecondary}`}>
              AI can make mistakes. Please review before use
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
